-- Populate desktime_employee_id and department for all active users
-- matched by email from DeskTime export (2026-03-31)

UPDATE public.users SET desktime_employee_id = 611263, department = 'Ortus Club' WHERE email = 'sam@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 611779, department = 'Ortus Club' WHERE email = 'jc@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 611780, department = 'Technology' WHERE email = 'mickey@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 611781, department = 'Ortus Club' WHERE email = 'mara@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 611783, department = 'Ortus Club' WHERE email = 'jamie@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 611824 WHERE email = 'anya@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 612183 WHERE email = 'driton@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 612184, department = 'Sales' WHERE email = 'flandra@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 613056, department = 'Team Frances' WHERE email = 'vito@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 613057, department = 'Team Benz' WHERE email = 'lawrence.bergado@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 613058, department = 'Team Benz' WHERE email = 'mishy@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 613059, department = 'Team Benz' WHERE email = 'reign.maitim@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 613367, department = 'Team Roman' WHERE email = 'roman@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 613368, department = 'Team Jessi' WHERE email = 'jessi@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 613369, department = 'Team Frances' WHERE email = 'frances@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 613370, department = 'Team Benz' WHERE email = 'benz@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 613484, department = 'Team Jessi' WHERE email = 'klarisse@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 613485, department = 'OA - FO Team' WHERE email = 'jeff.sumulong@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 613487, department = 'OA - FO Team' WHERE email = 'weng@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 613723, department = 'Team Jessi' WHERE email = 'raenvien.aniel@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 613739, department = 'Team Frances' WHERE email = 'cayla.gauna@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 613743, department = 'Team Jessi' WHERE email = 'karen.y@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 613806, department = 'OA - Research Team' WHERE email = 'ina@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 613807, department = 'OA - Research Team' WHERE email = 'pat.yanguas@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 613811, department = 'OA - Research Team' WHERE email = 'sam.salvador@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 613976, department = 'Team Roman' WHERE email = 'bea.talusan@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 613979, department = 'Team Roman' WHERE email = 'julia.m@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 613980, department = 'Team Jessi' WHERE email = 'chriss.rey@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 613981, department = 'Team Benz' WHERE email = 'gian.t@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 614052, department = 'OA - EWS and CRM' WHERE email = 'alecx@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 614233, department = 'Team Frances' WHERE email = 'joshua@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 614234, department = 'Team Benz' WHERE email = 'rapha.v@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 614236, department = 'Team Benz' WHERE email = 'charles.y@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 614418, department = 'Events' WHERE email = 'alyssa.constantino@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 615336, department = 'Team Diedona' WHERE email = 'andrrim.krenzi@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 615626, department = 'Team Diedona' WHERE email = 'antigona.brahimi@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 615629, department = 'Team Diedona' WHERE email = 'haris.fejza@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 615664, department = 'Team Bleron' WHERE email = 'gentrit.bislimi@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 615839, department = 'Team Bleron' WHERE email = 'bleron@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 615840, department = 'Team Nushe' WHERE email = 'nushe.himaj@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 615842, department = 'Team Diedona' WHERE email = 'qendresa.j@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 616062, department = 'Team Diedona' WHERE email = 'klara.d@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 621310, department = 'Technology' WHERE email = 'stevenj@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 621863, department = 'Team Diedona' WHERE email = 'bleronl@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 621943, department = 'Team Bleron' WHERE email = 'fluturai@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 623576, department = 'Sales' WHERE email = 'andrea@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 625633, department = 'Ortus Club' WHERE email = 'yosh@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 628685, department = 'OA - FO Team' WHERE email = 'ton@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 628687, department = 'OA - Research Team' WHERE email = 'bo@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 629561, department = 'Team Jessi' WHERE email = 'jhan@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 633647, department = 'Sales' WHERE email = 'sabrina@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 643185, department = 'Ortus Club' WHERE email = 'justin@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 645743, department = 'Events' WHERE email = 'yna@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 645744, department = 'Events' WHERE email = 'charlene.batongbakal@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 645745, department = 'Events' WHERE email = 'mozes.janse@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 645749, department = 'Events' WHERE email = 'aira@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 645750, department = 'Events' WHERE email = 'althea@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 645787, department = 'Sales' WHERE email = 'marcella@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 645788, department = 'Sales' WHERE email = 'neil@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 645789, department = 'Sales' WHERE email = 'ciara@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 645791, department = 'Sales' WHERE email = 'jovana@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 651715, department = 'Outbound Team' WHERE email = 'marigona@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 673014, department = 'Team Roman' WHERE email = 'daves@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 673016, department = 'Team Frances' WHERE email = 'jewel@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 673017, department = 'Team Frances' WHERE email = 'ricxel@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 673019, department = 'Team Benz' WHERE email = 'ej@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 677624, department = 'Team Bleron' WHERE email = 'dafina@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 677627, department = 'Team Nushe' WHERE email = 'adriana@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 677630, department = 'Team Nushe' WHERE email = 'elita@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 679551, department = 'Ortus Club' WHERE email = 'chalea@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 683176, department = 'Outbound Team' WHERE email = 'nikki@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 685881, department = 'OA - Research Team' WHERE email = 'kenji@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 686218, department = 'OA - FO Team' WHERE email = 'kobs@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 692278, department = 'Team Jessi' WHERE email = 'miggyg@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 699715, department = 'Team Frances' WHERE email = 'dannah@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 699716, department = 'Team Benz' WHERE email = 'khristian@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 701655, department = 'Team Bleron' WHERE email = 'met@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 701658, department = 'Team Bleron' WHERE email = 'eljesa@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 702757, department = 'Team Diedona' WHERE email = 'eriola@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 703064, department = 'Team Nushe' WHERE email = 'dion@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 704416, department = 'OA - Research Team' WHERE email = 'milac@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 715028, department = 'OA - FO Team' WHERE email = 'darrell@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 715029, department = 'OA - CRM and Linkedin' WHERE email = 'aby@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 715031, department = 'Team Benz' WHERE email = 'kamille@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 715032, department = 'Team Jessi' WHERE email = 'dwayne@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 715034, department = 'Outbound Team' WHERE email = 'nikolle@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 715036, department = 'Outbound Team' WHERE email = 'soleil@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 715040, department = 'Team Frances' WHERE email = 'asha@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 716064, department = 'Ortus Club' WHERE email = 'antonio@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 718758, department = 'Outbound Team' WHERE email = 'fatbardha@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 718759, department = 'Sales' WHERE email = 'ines@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 721516, department = 'Team Benz' WHERE email = 'lei@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 721517, department = 'Team Benz' WHERE email = 'nicko@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 721519, department = 'OA - EWS and CRM' WHERE email = 'shawn@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 722710, department = 'Team Benz' WHERE email = 'eena@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 723370, department = 'Team Diedona' WHERE email = 'arlinda@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 726254, department = 'Team Bleron' WHERE email = 'semra@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 726255, department = 'Team Diedona' WHERE email = 'flakron@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 726267, department = 'Team Bleron' WHERE email = 'rineta@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 727528, department = 'Team Nushe' WHERE email = 'yllkaq@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 727920, department = 'Team Diedona' WHERE email = 'verina@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 728260, department = 'Marketing' WHERE email = 'chayee@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 728763, department = 'OA - FO Team' WHERE email = 'cedric@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 730443, department = 'OA - FO Team' WHERE email = 'argil@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 731516, department = 'OA - CRM and Linkedin' WHERE email = 'zai@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 731517, department = 'OA - CRM and Linkedin' WHERE email = 'nabeen@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 731518, department = 'OA - CRM and Linkedin' WHERE email = 'audrey@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 731522, department = 'Marketing' WHERE email = 'maxine@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 731523, department = 'Marketing' WHERE email = 'carmen@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 731524, department = 'Marketing' WHERE email = 'allen@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 732621, department = 'Events' WHERE email = 'antonp@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 732622, department = 'Events' WHERE email = 'chay@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 734231, department = 'Marketing' WHERE email = 'angellie@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 741624, department = 'Events' WHERE email = 'clyde@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 742178, department = 'Sales' WHERE email = 'otero@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 742966, department = 'Team Benz' WHERE email = 'nicole.soberano@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 742967, department = 'Team Benz' WHERE email = 'janne@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 742968, department = 'Team Jessi' WHERE email = 'adri@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 742969, department = 'Team Jessi' WHERE email = 'aima@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 744213, department = 'Marketing' WHERE email = 'sherby@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 748229, department = 'Ortus Club' WHERE email = 'community@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 750246, department = 'Team Roman' WHERE email = 'ivy@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 750247, department = 'Team Frances' WHERE email = 'joelea@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 750248, department = 'Team Frances' WHERE email = 'joaquin@ortusclub.com';
UPDATE public.users SET desktime_employee_id = 750249, department = 'Team Benz' WHERE email = 'rein@ortusclub.com';
